version: '3.9'
services:
  app:
    build: .
    image: my-java-app-image:latest
    environment:
      DATASOURCE_URL: jdbc:mysql://sql-1:3306/new_database
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
      - apache
  apache:
    image: httpd
    ports:
      - "80:80"
  db:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - database:/var/lib/mysql
volumes:
  database: {}