version: "3.8"
services:
 server:
    image: nginx:latest
    volumes:
      - ./server/:/usr/share/nginx/html/
    ports:
      - "1234:80" 
 client:
    build: client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server